config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'
  resources :posts
  get :'', to: 'posts#index'
  get :guilty, to: 'posts#guilty'
  get :not_guilty, to: 'posts#not_guilty'
  get :little_guilty, to: 'posts#little_guilty'
  get :little_not_guilty, to: 'posts#little_not_guilty'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true, length: { maximum: 140 }
  validates :kind, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   add_flash_types :success, :info, :warning, :danger
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, success: "投稿しました"
          # ContactMailer.contact_mail(@post).deliver
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), success: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def show
  end

  def guilty
    if params[:post_id].present?
      @post = Post.find(params[:post_id])
      @post.guilty += 1
      @post.save
      redirect_to post_path(@post.id), info: "ハラスメント！に投票!"
    else
      render :index
    end
  end

  def not_guilty
    if params[:post_id].present?
      @post = Post.find(params[:post_id])
      @post.not_guilty += 1
      @post.save
      redirect_to post_path(@post.id), info: "ちがうに投票！"
    else
      render :index
    end
  end

  def little_guilty
    if params[:post_id].present?
      @post = Post.find(params[:post_id])
      @post.little_guilty += 1
      @post.save
      redirect_to post_path(@post.id), info: "多分そうに投票!"
    else
      render :index
    end
  end

  def little_not_guilty
    if params[:post_id].present?
      @post = Post.find(params[:post_id])
      @post.little_not_guilty += 1
      @post.save
      redirect_to post_path(@post.id), info: "多分ちがうに投票!"
    else
      render :index
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, danger: "投稿を削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:title, :kind)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
  base_title = 'これってハラスメント？'

  page_title.empty? ? base_title : page_title + " | " + base_title
  end

  def admin_page_title(admin_page_title = '')
  base_title = 'これってハラスメント？(管理画面)'

  page_title.empty? ? base_title : admin_page_title + ' | ' + base_title
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = page_title(yield(:title))
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"

  body
    = render 'shared/header'
    = render 'shared/flash_message'
    = yield

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'された行動、言動など' %>
  </div>
  <div class="form-group">
    <%= f.label :kind %>
    <%= f.text_field :kind, class: 'form-control', placeholder: '例：パワハラ、セクハラ、モラハラ、マタハラなど' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div class="col-sm-10 col-md-10 col-lg-10 mb-2">
  <div id="post-id-<%= post.id %>">
    <div class="card mb-3" style="max-width: 1000px;">
      <!-- グラフとテキストを横並びにする -->
      <div class="row no-gutters">
        <!-- テキスト部分 -->
        <div class="col-lg-6">
          <div class="card-body">
            <li class="list-inline-item" id="kind_button">
              <%= "#{post.kind}"%>
            </li>
            <h4 class="card-text base-light-color">
              <%= link_to post.title, post_path(post.id) %>
            </h4>
            <ul class="list-inline">
              <li class="list-inline-item">
                <%= link_to guilty_path(post_id: post.id), class: 'btn btn-light-blue btn-sm', method: :get do %>
                  ハラスメント！
                <% end %>
                <%= "#{post.guilty}票"%>
              </li>
              <li class="list-inline-item">
                <%= link_to little_guilty_path(post_id: post.id), class: 'btn btn-light-green btn-sm', method: :get do %>
                  たぶんそう
                <% end %>
                <%= "#{post.little_guilty}票"%>
              </li>
              <li class="list-inline-item">
                <%= link_to little_not_guilty_path(post_id: post.id), class: 'btn btn-orange btn-sm', method: :get do %>
                  たぶんちがう
                <% end %>
                <%= "#{post.little_not_guilty}票"%>
              </li>
              <li class="list-inline-item">
                <%= link_to not_guilty_path(post_id: post.id), class: 'btn btn-pink btn-sm', method: :get do %>
                  ちがう
                <% end %>
                <%= "#{post.not_guilty}票"%>
              </li>
            </ul>
          </div>
        </div>
        <!-- グラフ部分 -->
        <div class="col-lg-6">
          <% unless post.guilty == 0 && post.not_guilty == 0 && post.little_guilty == 0 && post.little_not_guilty == 0 %>
            <%= pie_chart [ ["ハラスメント",post.guilty],
                            ["ちがう",post.not_guilty],
                            ["多分ちがう",post.little_not_guilty],
                            ["多分そう",post.little_guilty] ]%>
          <% else %>
            <p>まだ投票されていません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="input-group">
    <%= f.search_field :title_or_kind_cont, class: 'form-control' %>
    <div class="input-group-append">
      <%= f.submit '検索', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>

<div class="container pt-3">
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <!-- サーチフォーム -->
      <div class="row">
        <div class="col-8 offset-2 mb-3">
          <%= render 'search_form', url: posts_path, class:'form-inline' %>
        </div>
      </div>
      <!-- サーチフォームここまで -->
      <div class="row">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
  <!-- ページネーション -->
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render @post %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.slim
header
  nav.navbar.navigation.navbar-light.base-color
    = link_to posts_path, class: 'navbar-brand' do
      |  これってハラスメント？
    #navbarSupportedContent
      .navbar
          = link_to new_post_path
            |   新規作成

          = link_to "https://twitter.com/share?url=#{ request.url }&text=これってハラスメント？みんなでハラスメントか投票しよう！", target: '_blank' do
            i.fab.fa-twitter.fa-2x style='color: #3399FF; background-color: white; border-radius: 10px;'
            |